[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "conda-pack"
dynamic = ["version"]
description = "Package conda environments for redistribution"
readme = "README.md"
license = {text = "BSD"}
authors = [
    {name = "Jim Crist", email = "jiminy.crist@gmail.com"}
]
keywords = ["conda", "packaging"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Archiving :: Packaging",
    "Topic :: System :: Software Distribution",
    "Topic :: Software Development :: Build Tools",
]
requires-python = ">=3.8"
dependencies = [
    "setuptools",
]

[project.urls]
Homepage = "https://conda.github.io/conda-pack/"
Repository = "https://github.com/conda/conda-pack"
Documentation = "https://conda.github.io/conda-pack/"

[project.scripts]
conda-pack = "conda_pack.cli:main"

[tool.setuptools]
packages = ["conda_pack"]
package-data = {conda_pack = ["scripts/windows/*", "scripts/posix/*"]}
zip-safe = false

[tool.setuptools-scm]
write_to = "conda_pack/_version.py"
write_to_template = """
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = {version!r}
__version_tuple__ = version_tuple = {version_tuple!r}
"""

[tool.setuptools-scm.local_scheme]
version_scheme = "python-simplified-semver"
local_scheme = "node-and-timestamp"

# Development dependencies
[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=23.0",
    "isort>=5.0",
    "flake8>=6.0",
    "pre-commit>=3.0",
]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
docs = [
    "sphinx>=6.0",
    "sphinx-rtd-theme>=1.0",
    "myst-parser>=1.0",
    "sphinx-autodoc-typehints>=1.0",
    "sphinx-copybutton>=0.5",
    "sphinxext-opengraph>=0.8",
]

# Tool configurations
[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.flake8]
max-line-length = 100
exclude = ["__init__.py", "conda_pack/_version.py"]

[tool.pytest.ini_options]
testpaths = ["conda_pack/tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=conda_pack",
    "--cov-report=term-missing",
    "--cov-report=xml",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
]
